// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using loghid.Data;

#nullable disable

namespace loghid.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250202030700_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("loghid.Models.ContaminantParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContaminantParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaxLimit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContaminantParameterId");

                    b.ToTable("ContaminantParameters");
                });

            modelBuilder.Entity("loghid.Models.IdealParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdealParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdealParameterId");

                    b.ToTable("IdealParameters");
                });

            modelBuilder.Entity("loghid.Models.ContaminantParameter", b =>
                {
                    b.HasOne("loghid.Models.ContaminantParameter", null)
                        .WithMany("Contaminants")
                        .HasForeignKey("ContaminantParameterId");
                });

            modelBuilder.Entity("loghid.Models.IdealParameter", b =>
                {
                    b.HasOne("loghid.Models.IdealParameter", null)
                        .WithMany("IdealParameters")
                        .HasForeignKey("IdealParameterId");
                });

            modelBuilder.Entity("loghid.Models.ContaminantParameter", b =>
                {
                    b.Navigation("Contaminants");
                });

            modelBuilder.Entity("loghid.Models.IdealParameter", b =>
                {
                    b.Navigation("IdealParameters");
                });
#pragma warning restore 612, 618
        }
    }
}
