// <auto-generated />
using System;
using Loghid.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace loghid.Migrations
{
    [DbContext(typeof(LoghidClientMeasurementDbContext))]
    [Migration("20250205212703_LoghidMeasurementDbContext36345")]
    partial class LoghidMeasurementDbContext36345
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Loghid.Models.ClientMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("MeasurementDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("Loghid.Models.Substance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Substance");
                });
#pragma warning restore 612, 618
        }
    }
}
