// <auto-generated />
using Loghid.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace loghid.Migrations
{
    [DbContext(typeof(SprinterLabShimadzuGC2030DbContext))]
    [Migration("20250208225859_alfam14")]
    partial class alfam14
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Loghid.Models.SprinterLabShimadzuGC2030", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CapacidadCarga")
                        .HasColumnType("REAL");

                    b.Property<string>("CarrierAlternativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarrierGas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectorAzufre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectorHidrocarburos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectorHidrogeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectorOxigenoOtros")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnsayoCalidadHidrogeno")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnsayoFugas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnsayoPresion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<double>("EspacioInterior")
                        .HasColumnType("REAL");

                    b.Property<int>("FiltroMaximoMicrones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiltroMinimoMicrones")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetodoCalibracion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoTomaMuestra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeloEquipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormaCalibracion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormaHidrogeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormaPureza")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PurezaMinima")
                        .HasColumnType("REAL");

                    b.Property<double>("PurezaOptima")
                        .HasColumnType("REAL");

                    b.Property<double>("SensibilidadMinima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.10000000000000001);

                    b.Property<bool>("SistemaAislamientoVibraciones")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SistemaClimatizacionControlada")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SistemaEnergiaIndependiente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoConversion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadContenidoAgua")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadFraccionMolar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadImpurezas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vehiculo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Mercedes-Benz Sprinter");

                    b.HasKey("Id");

                    b.HasIndex("ModeloEquipo")
                        .IsUnique();

                    b.HasIndex("NormaHidrogeno");

                    b.HasIndex("PurezaOptima");

                    b.ToTable("SprinterLabs");
                });
#pragma warning restore 612, 618
        }
    }
}
