// <auto-generated />
using Loghid.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace loghid.Migrations
{
    [DbContext(typeof(eSprinterLabShimadzuDbContext))]
    [Migration("20250210204333_mi3")]
    partial class mi3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Loghid.Models.eSprinterLab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AirFuelGas")
                        .HasColumnType("REAL");

                    b.Property<double>("AnalysisService")
                        .HasColumnType("REAL");

                    b.Property<double>("AutonomyCapacity")
                        .HasColumnType("REAL");

                    b.Property<double>("Calibration")
                        .HasColumnType("REAL");

                    b.Property<double>("CargoCapacity")
                        .HasColumnType("REAL");

                    b.Property<double>("Chromatograph")
                        .HasColumnType("REAL");

                    b.Property<double>("ChromatographCertification")
                        .HasColumnType("REAL");

                    b.Property<double>("FID")
                        .HasColumnType("REAL");

                    b.Property<double>("FPD")
                        .HasColumnType("REAL");

                    b.Property<double>("GasColumns")
                        .HasColumnType("REAL");

                    b.Property<double>("HeliumCarrierGas")
                        .HasColumnType("REAL");

                    b.Property<double>("Hygrometer")
                        .HasColumnType("REAL");

                    b.Property<double>("InteriorSpace")
                        .HasColumnType("REAL");

                    b.Property<double>("PressureRegulators")
                        .HasColumnType("REAL");

                    b.Property<double>("PricePer100km")
                        .HasColumnType("REAL");

                    b.Property<double>("RegulatoryConsultations")
                        .HasColumnType("REAL");

                    b.Property<double>("StandardGasBottles")
                        .HasColumnType("REAL");

                    b.Property<double>("TCD")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[VehiclePrice] + [Chromatograph] + [TCD] + [FID] + [Hygrometer] + [FPD] + [PressureRegulators] + [StandardGasBottles] + [GasColumns] + [HeliumCarrierGas] + [AirFuelGas] + [ChromatographCertification] + [RegulatoryConsultations] + [AnalysisService] + [Calibration] + [VehicleMaintenance]", false);

                    b.Property<string>("Vehicle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("VehicleMaintenance")
                        .HasColumnType("REAL");

                    b.Property<double>("VehiclePrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("eSprinterLab");
                });
#pragma warning restore 612, 618
        }
    }
}
