// <auto-generated />
using Loghid.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace loghid.Migrations
{
    [DbContext(typeof(SprinterLabShimadzuGC2030DbContext))]
    [Migration("20250208214819_alfam11")]
    partial class alfam11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Precio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("PrecioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RangoPrecio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sistema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Precios");
                });

            modelBuilder.Entity("SprinterLabShimadzuGC2030", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CapacidadCarga")
                        .HasColumnType("REAL");

                    b.Property<string>("CarrierAlternativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarrierGas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectorAzufre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectorHidrocarburos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectorHidrogeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectorOxigenoOtros")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnsayoCalidadHidrogeno")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnsayoFugas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnsayoPresion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<double>("EspacioInterior")
                        .HasColumnType("REAL");

                    b.Property<int>("FiltroMaximoMicrones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiltroMinimoMicrones")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetodoCalibracion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoTomaMuestra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeloEquipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormaCalibracion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormaHidrogeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormaPureza")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrecioCarrierAlternativoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioCarrierGasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioDetectorAzufreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioDetectorHidrocarburosId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioDetectorHidrogenoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioDetectorOxigenoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioEnsayoCalidadHidrogenoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioEnsayoFugasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioEnsayoPresionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioFiltradoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioMetodoCalibracionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioMetodoTomaMuestraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioModeloEquipoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioNormaCalibracionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioNormaHidrogenoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioNormaPurezaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioSensibilidadMinimaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioSistemaAislamientoVibracionesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioSistemaClimatizacionControladaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioSistemaEnergiaIndependienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioTipoConversionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioUnidadContenidoAguaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioUnidadFraccionMolarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioUnidadImpurezasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrecioVehiculoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PurezaMinima")
                        .HasColumnType("REAL");

                    b.Property<double>("PurezaOptima")
                        .HasColumnType("REAL");

                    b.Property<double>("SensibilidadMinima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.10000000000000001);

                    b.Property<bool>("SistemaAislamientoVibraciones")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SistemaClimatizacionControlada")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SistemaEnergiaIndependiente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoConversion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadContenidoAgua")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadFraccionMolar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadImpurezas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vehiculo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Mercedes-Benz Sprinter");

                    b.HasKey("Id");

                    b.HasIndex("ModeloEquipo")
                        .IsUnique();

                    b.HasIndex("NormaHidrogeno");

                    b.HasIndex("PrecioCarrierAlternativoId");

                    b.HasIndex("PrecioCarrierGasId");

                    b.HasIndex("PrecioDetectorAzufreId");

                    b.HasIndex("PrecioDetectorHidrocarburosId");

                    b.HasIndex("PrecioDetectorHidrogenoId");

                    b.HasIndex("PrecioDetectorOxigenoId");

                    b.HasIndex("PrecioEnsayoCalidadHidrogenoId");

                    b.HasIndex("PrecioEnsayoFugasId");

                    b.HasIndex("PrecioEnsayoPresionId");

                    b.HasIndex("PrecioFiltradoId");

                    b.HasIndex("PrecioMetodoCalibracionId");

                    b.HasIndex("PrecioMetodoTomaMuestraId");

                    b.HasIndex("PrecioModeloEquipoId");

                    b.HasIndex("PrecioNormaCalibracionId");

                    b.HasIndex("PrecioNormaHidrogenoId");

                    b.HasIndex("PrecioNormaPurezaId");

                    b.HasIndex("PrecioSensibilidadMinimaId");

                    b.HasIndex("PrecioSistemaAislamientoVibracionesId");

                    b.HasIndex("PrecioSistemaClimatizacionControladaId");

                    b.HasIndex("PrecioSistemaEnergiaIndependienteId");

                    b.HasIndex("PrecioTipoConversionId");

                    b.HasIndex("PrecioUnidadContenidoAguaId");

                    b.HasIndex("PrecioUnidadFraccionMolarId");

                    b.HasIndex("PrecioUnidadImpurezasId");

                    b.HasIndex("PrecioVehiculoId");

                    b.HasIndex("PurezaOptima");

                    b.ToTable("SprinterLabs");
                });

            modelBuilder.Entity("SprinterLabShimadzuGC2030", b =>
                {
                    b.HasOne("Precio", "PrecioCarrierAlternativo")
                        .WithMany()
                        .HasForeignKey("PrecioCarrierAlternativoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioCarrierGas")
                        .WithMany()
                        .HasForeignKey("PrecioCarrierGasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioDetectorAzufre")
                        .WithMany()
                        .HasForeignKey("PrecioDetectorAzufreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioDetectorHidrocarburos")
                        .WithMany()
                        .HasForeignKey("PrecioDetectorHidrocarburosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioDetectorHidrogeno")
                        .WithMany()
                        .HasForeignKey("PrecioDetectorHidrogenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioDetectorOxigeno")
                        .WithMany()
                        .HasForeignKey("PrecioDetectorOxigenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioEnsayoCalidadHidrogeno")
                        .WithMany()
                        .HasForeignKey("PrecioEnsayoCalidadHidrogenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioEnsayoFugas")
                        .WithMany()
                        .HasForeignKey("PrecioEnsayoFugasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioEnsayoPresion")
                        .WithMany()
                        .HasForeignKey("PrecioEnsayoPresionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioFiltrado")
                        .WithMany()
                        .HasForeignKey("PrecioFiltradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioMetodoCalibracion")
                        .WithMany()
                        .HasForeignKey("PrecioMetodoCalibracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioMetodoTomaMuestra")
                        .WithMany()
                        .HasForeignKey("PrecioMetodoTomaMuestraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioModeloEquipo")
                        .WithMany()
                        .HasForeignKey("PrecioModeloEquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioNormaCalibracion")
                        .WithMany()
                        .HasForeignKey("PrecioNormaCalibracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioNormaHidrogeno")
                        .WithMany()
                        .HasForeignKey("PrecioNormaHidrogenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioNormaPureza")
                        .WithMany()
                        .HasForeignKey("PrecioNormaPurezaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioSensibilidadMinima")
                        .WithMany()
                        .HasForeignKey("PrecioSensibilidadMinimaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioSistemaAislamientoVibraciones")
                        .WithMany()
                        .HasForeignKey("PrecioSistemaAislamientoVibracionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioSistemaClimatizacionControlada")
                        .WithMany()
                        .HasForeignKey("PrecioSistemaClimatizacionControladaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioSistemaEnergiaIndependiente")
                        .WithMany()
                        .HasForeignKey("PrecioSistemaEnergiaIndependienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioTipoConversion")
                        .WithMany()
                        .HasForeignKey("PrecioTipoConversionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioUnidadContenidoAgua")
                        .WithMany()
                        .HasForeignKey("PrecioUnidadContenidoAguaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioUnidadFraccionMolar")
                        .WithMany()
                        .HasForeignKey("PrecioUnidadFraccionMolarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioUnidadImpurezas")
                        .WithMany()
                        .HasForeignKey("PrecioUnidadImpurezasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Precio", "PrecioVehiculo")
                        .WithMany()
                        .HasForeignKey("PrecioVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrecioCarrierAlternativo");

                    b.Navigation("PrecioCarrierGas");

                    b.Navigation("PrecioDetectorAzufre");

                    b.Navigation("PrecioDetectorHidrocarburos");

                    b.Navigation("PrecioDetectorHidrogeno");

                    b.Navigation("PrecioDetectorOxigeno");

                    b.Navigation("PrecioEnsayoCalidadHidrogeno");

                    b.Navigation("PrecioEnsayoFugas");

                    b.Navigation("PrecioEnsayoPresion");

                    b.Navigation("PrecioFiltrado");

                    b.Navigation("PrecioMetodoCalibracion");

                    b.Navigation("PrecioMetodoTomaMuestra");

                    b.Navigation("PrecioModeloEquipo");

                    b.Navigation("PrecioNormaCalibracion");

                    b.Navigation("PrecioNormaHidrogeno");

                    b.Navigation("PrecioNormaPureza");

                    b.Navigation("PrecioSensibilidadMinima");

                    b.Navigation("PrecioSistemaAislamientoVibraciones");

                    b.Navigation("PrecioSistemaClimatizacionControlada");

                    b.Navigation("PrecioSistemaEnergiaIndependiente");

                    b.Navigation("PrecioTipoConversion");

                    b.Navigation("PrecioUnidadContenidoAgua");

                    b.Navigation("PrecioUnidadFraccionMolar");

                    b.Navigation("PrecioUnidadImpurezas");

                    b.Navigation("PrecioVehiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
