// <auto-generated />
using Loghid.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace loghid.Migrations
{
    [DbContext(typeof(LoghidDbContext))]
    [Migration("20250203102354_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Loghid.Models.Ammonia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResult")
                        .HasColumnType("REAL");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ammonia");
                });

            modelBuilder.Entity("Loghid.Models.Argon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResult")
                        .HasColumnType("REAL");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Argon");
                });

            modelBuilder.Entity("Loghid.Models.CarbonDioxide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResultMax")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResultMin")
                        .HasColumnType("REAL");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarbonDioxide");
                });

            modelBuilder.Entity("Loghid.Models.CarbonMonoxide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResult")
                        .HasColumnType("REAL");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarbonMonoxide");
                });

            modelBuilder.Entity("Loghid.Models.Formaldehyde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResult")
                        .HasColumnType("REAL");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Formaldehyde");
                });

            modelBuilder.Entity("Loghid.Models.FormicAcid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResult")
                        .HasColumnType("REAL");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FormicAcid");
                });

            modelBuilder.Entity("Loghid.Models.HalogenatedCompounds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResult")
                        .HasColumnType("REAL");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HalogenatedCompounds");
                });

            modelBuilder.Entity("Loghid.Models.Helium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResultMax")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResultMin")
                        .HasColumnType("REAL");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Helium");
                });

            modelBuilder.Entity("Loghid.Models.Hydrocarbons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResultC2")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResultC3")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResultC4")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResultC5")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResultC6C18")
                        .HasColumnType("REAL");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hydrocarbons");
                });

            modelBuilder.Entity("Loghid.Models.Methane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResult")
                        .HasColumnType("REAL");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Methane");
                });

            modelBuilder.Entity("Loghid.Models.Nitrogen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResultMax")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResultMin")
                        .HasColumnType("REAL");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nitrogen");
                });

            modelBuilder.Entity("Loghid.Models.NonCH4Hydrocarbons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResultMax")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResultMin")
                        .HasColumnType("REAL");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NonCH4Hydrocarbons");
                });

            modelBuilder.Entity("Loghid.Models.Oxygen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResultMax")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResultMin")
                        .HasColumnType("REAL");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Oxygen");
                });

            modelBuilder.Entity("Loghid.Models.SulphurCompounds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResult")
                        .HasColumnType("REAL");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SulphurCompounds");
                });

            modelBuilder.Entity("Loghid.Models.Water", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("PemResult")
                        .HasColumnType("REAL");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Water");
                });
#pragma warning restore 612, 618
        }
    }
}
