// <auto-generated />
using System;
using Loghid.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace loghid.Migrations
{
    [DbContext(typeof(LoghidClientMeasurementDbContext))]
    [Migration("20250206003355_alfam9")]
    partial class alfam9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Loghid.Models.ClientMeasurement", b =>
                {
                    b.Property<int>("Id_Measurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amonia_IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("Amonia_MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Amonia_MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Amonia_Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Amonia_SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Argon_IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("Argon_MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Argon_MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Argon_Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Argon_SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CarbonDioxide_Argon_IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("CarbonDioxide_Argon_MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarbonDioxide_Argon_MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarbonDioxide_Argon_Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarbonDioxide_SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CarbonMonoxid_IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("CarbonMonoxid_MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarbonMonoxid_MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarbonMonoxid_Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarbonMonoxid_SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerID_Measurement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Customer_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Date_Measurement")
                        .HasColumnType("TEXT");

                    b.Property<double>("Formaldehyde_IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("Formaldehyde_MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formaldehyde_MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formaldehyde_Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formaldehyde_SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FormicAcid_IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("FormicAcid_MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormicAcid_MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormicAcid_Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormicAcid_SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("HalogenatedCompounds_IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("HalogenatedCompounds_MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HalogenatedCompounds_MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HalogenatedCompounds_Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HalogenatedCompounds_SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Helium_IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("Helium_MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Helium_MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Helium_Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Helium_SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Hydrocarbons_IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("Hydrocarbons_MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hydrocarbons_MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hydrocarbons_Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hydrocarbons_SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Methane_IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("Methane_MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Methane_MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Methane_Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Methane_SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Nitrogen_IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("Nitrogen_MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nitrogen_MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nitrogen_Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nitrogen_SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NonCH4Hydrocarbons_IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("NonCH4Hydrocarbons_MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NonCH4Hydrocarbons_MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NonCH4Hydrocarbons_Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NonCH4Hydrocarbons_SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes_Measurement")
                        .HasColumnType("TEXT");

                    b.Property<double>("Oxygen_IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("Oxygen_MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Oxygen_MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Oxygen_Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Oxygen_SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicID_Measurement")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(19)
                        .HasColumnType("TEXT");

                    b.Property<double>("SulphurCompounds_IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("SulphurCompounds_MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SulphurCompounds_MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SulphurCompounds_Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SulphurCompounds_SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierID_Measurement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Supplier_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Water_ISO_Threshold_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Water_MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Water_Measurement_Method_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Water_Name_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Water_Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Measurement");

                    b.HasIndex("PublicID_Measurement")
                        .IsUnique();

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("Loghid.Models.Substance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Substances");
                });
#pragma warning restore 612, 618
        }
    }
}
