// <auto-generated />
using System;
using Loghid.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace loghid.Migrations
{
    [DbContext(typeof(LoghidClientMeasurementDbContext))]
    [Migration("20250205225530_alfam3")]
    partial class alfam3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Loghid.Models.AmmoniaMeasurement", b =>
                {
                    b.Property<int>("Id_Measurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Measurement");

                    b.ToTable("AmmoniaMeasurements");
                });

            modelBuilder.Entity("Loghid.Models.ArgonMeasurement", b =>
                {
                    b.Property<int>("Id_Measurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Measurement");

                    b.ToTable("ArgonMeasurements");
                });

            modelBuilder.Entity("Loghid.Models.CarbonDioxideMeasurement", b =>
                {
                    b.Property<int>("Id_Measurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Measurement");

                    b.ToTable("CarbonDioxideMeasurements");
                });

            modelBuilder.Entity("Loghid.Models.CarbonMonoxidMeasurement", b =>
                {
                    b.Property<int>("Id_Measurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Measurement");

                    b.ToTable("CarbonMonoxideMeasurements");
                });

            modelBuilder.Entity("Loghid.Models.ClientMeasurement", b =>
                {
                    b.Property<int>("Id_Measurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Date_Measurement")
                        .HasColumnType("TEXT");

                    b.Property<double>("IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("Location_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes_Measurement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value_Measurement")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Measurement");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("Loghid.Models.FormaldehydeMeasurement", b =>
                {
                    b.Property<int>("Id_Measurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Measurement");

                    b.ToTable("FormaldehydeMeasurements");
                });

            modelBuilder.Entity("Loghid.Models.FormicAcidMeasurement", b =>
                {
                    b.Property<int>("Id_Measurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Measurement");

                    b.ToTable("FormicAcidMeasurements");
                });

            modelBuilder.Entity("Loghid.Models.HalogenatedCompoundsMeasurement", b =>
                {
                    b.Property<int>("Id_Measurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Measurement");

                    b.ToTable("HalogenatedCompoundsMeasurements");
                });

            modelBuilder.Entity("Loghid.Models.HeliumMeasurement", b =>
                {
                    b.Property<int>("Id_Measurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Measurement");

                    b.ToTable("HeliumMeasurements");
                });

            modelBuilder.Entity("Loghid.Models.HydrocarbonsMeasurement", b =>
                {
                    b.Property<int>("Id_Measurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Measurement");

                    b.ToTable("HydrocarbonsMeasurements");
                });

            modelBuilder.Entity("Loghid.Models.NitrogenMeasurement", b =>
                {
                    b.Property<int>("Id_Measurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Measurement");

                    b.ToTable("NitrogenMeasurements");
                });

            modelBuilder.Entity("Loghid.Models.OxygenMeasurement", b =>
                {
                    b.Property<int>("Id_Measurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Measurement");

                    b.ToTable("OxygenMeasurements");
                });

            modelBuilder.Entity("Loghid.Models.Substance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Substances");
                });

            modelBuilder.Entity("Loghid.Models.SulphurCompoundsMeasurement", b =>
                {
                    b.Property<int>("Id_Measurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Measurement");

                    b.ToTable("SulphurCompoundsMeasurements");
                });

            modelBuilder.Entity("Loghid.Models.WaterMeasurement", b =>
                {
                    b.Property<int>("Id_Measurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold_Measurement")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName_Measurement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Measurement");

                    b.ToTable("WaterMeasurements");
                });

            modelBuilder.Entity("Loghid.Models.AmmoniaMeasurement", b =>
                {
                    b.HasOne("Loghid.Models.ClientMeasurement", null)
                        .WithMany()
                        .HasForeignKey("Id_Measurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loghid.Models.ArgonMeasurement", b =>
                {
                    b.HasOne("Loghid.Models.ClientMeasurement", null)
                        .WithMany()
                        .HasForeignKey("Id_Measurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loghid.Models.CarbonDioxideMeasurement", b =>
                {
                    b.HasOne("Loghid.Models.ClientMeasurement", null)
                        .WithMany()
                        .HasForeignKey("Id_Measurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loghid.Models.FormaldehydeMeasurement", b =>
                {
                    b.HasOne("Loghid.Models.ClientMeasurement", null)
                        .WithMany()
                        .HasForeignKey("Id_Measurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loghid.Models.FormicAcidMeasurement", b =>
                {
                    b.HasOne("Loghid.Models.ClientMeasurement", null)
                        .WithMany()
                        .HasForeignKey("Id_Measurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loghid.Models.HalogenatedCompoundsMeasurement", b =>
                {
                    b.HasOne("Loghid.Models.ClientMeasurement", null)
                        .WithMany()
                        .HasForeignKey("Id_Measurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loghid.Models.HeliumMeasurement", b =>
                {
                    b.HasOne("Loghid.Models.ClientMeasurement", null)
                        .WithMany()
                        .HasForeignKey("Id_Measurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loghid.Models.HydrocarbonsMeasurement", b =>
                {
                    b.HasOne("Loghid.Models.ClientMeasurement", null)
                        .WithMany()
                        .HasForeignKey("Id_Measurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loghid.Models.NitrogenMeasurement", b =>
                {
                    b.HasOne("Loghid.Models.ClientMeasurement", null)
                        .WithMany()
                        .HasForeignKey("Id_Measurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loghid.Models.OxygenMeasurement", b =>
                {
                    b.HasOne("Loghid.Models.ClientMeasurement", null)
                        .WithMany()
                        .HasForeignKey("Id_Measurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loghid.Models.SulphurCompoundsMeasurement", b =>
                {
                    b.HasOne("Loghid.Models.ClientMeasurement", null)
                        .WithMany()
                        .HasForeignKey("Id_Measurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loghid.Models.WaterMeasurement", b =>
                {
                    b.HasOne("Loghid.Models.ClientMeasurement", null)
                        .WithMany()
                        .HasForeignKey("Id_Measurement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
