// <auto-generated />
using System;
using LoghidMeasurement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace loghid.Migrations
{
    [DbContext(typeof(LoghidMeasurementDbContext))]
    partial class LoghidMeasurementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Loghid.Models.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("MeasurementDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubstanceId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubstanceId");

                    b.HasIndex("SubstanceId1");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("Loghid.Models.Substance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Substances");
                });

            modelBuilder.Entity("Loghid.Models.Measurement", b =>
                {
                    b.HasOne("Loghid.Models.Substance", "Substance")
                        .WithMany()
                        .HasForeignKey("SubstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loghid.Models.Substance", null)
                        .WithMany("Measurements")
                        .HasForeignKey("SubstanceId1");

                    b.Navigation("Substance");
                });

            modelBuilder.Entity("Loghid.Models.Substance", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
