// <auto-generated />
using Loghid.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace loghid.Migrations
{
    [DbContext(typeof(SprinterLabShimadzuDbContext))]
    partial class SprinterLabShimadzuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Loghid.Models.SprinterLab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternativeCarrier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AlternativeCarrierPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalibrationMethod")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CalibrationMethodPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalibrationStandard")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CalibrationStandardPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarrierGas")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CarrierGasPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ControlledClimateSystem")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ControlledClimateSystemPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversionType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConversionTypePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EquipmentModelPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("HydrocarbonDetector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HydrocarbonDetectorPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("HydrogenDetector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HydrogenDetectorPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HydrogenQualityTest")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HydrogenQualityTestPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("HydrogenStandard")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HydrogenStandardPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpuritiesUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImpuritiesUnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IndependentPowerSystem")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IndependentPowerSystemPrice")
                        .HasColumnType("TEXT");

                    b.Property<double>("InteriorSpace")
                        .HasColumnType("REAL");

                    b.Property<decimal>("InteriorSpacePrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LeakTest")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LeakTestPrice")
                        .HasColumnType("TEXT");

                    b.Property<double>("LoadCapacity")
                        .HasColumnType("REAL");

                    b.Property<decimal>("LoadCapacityPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumMicronFilter")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaximumMicronFilterPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumMicronFilter")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinimumMicronFilterPrice")
                        .HasColumnType("TEXT");

                    b.Property<double>("MinimumPurity")
                        .HasColumnType("REAL");

                    b.Property<decimal>("MinimumPurityPrice")
                        .HasColumnType("TEXT");

                    b.Property<double>("MinimumSensitivity")
                        .HasColumnType("REAL");

                    b.Property<decimal>("MinimumSensitivityPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("MolarFractionUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MolarFractionUnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<double>("OptimalPurity")
                        .HasColumnType("REAL");

                    b.Property<decimal>("OptimalPurityPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("OxygenOthersDetector")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OxygenOthersDetectorPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PressureTest")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PressureTestPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurityStandard")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurityStandardPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleCollectionMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SampleCollectionMethodPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("SulfurDetector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SulfurDetectorPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vehicle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VehiclePrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("VibrationIsolationSystem")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VibrationIsolationSystemPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("WaterContentUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WaterContentUnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SprinterLab");
                });
#pragma warning restore 612, 618
        }
    }
}
