// <auto-generated />
using Loghid.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace loghid.Migrations.LoghidDb
{
    [DbContext(typeof(LoghidDbContext))]
    partial class LoghidDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Loghid.Models.Ammonia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ammonia", (string)null);
                });

            modelBuilder.Entity("Loghid.Models.Argon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Argon", (string)null);
                });

            modelBuilder.Entity("Loghid.Models.CarbonDioxide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarbonDioxide", (string)null);
                });

            modelBuilder.Entity("Loghid.Models.CarbonMonoxide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarbonMonoxide", (string)null);
                });

            modelBuilder.Entity("Loghid.Models.Formaldehyde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Formaldehyde", (string)null);
                });

            modelBuilder.Entity("Loghid.Models.FormicAcid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FormicAcid", (string)null);
                });

            modelBuilder.Entity("Loghid.Models.HalogenatedCompounds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HalogenatedCompounds", (string)null);
                });

            modelBuilder.Entity("Loghid.Models.Helium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Helium", (string)null);
                });

            modelBuilder.Entity("Loghid.Models.Hydrocarbons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hydrocarbons", (string)null);
                });

            modelBuilder.Entity("Loghid.Models.Methane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Methane", (string)null);
                });

            modelBuilder.Entity("Loghid.Models.Nitrogen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nitrogen", (string)null);
                });

            modelBuilder.Entity("Loghid.Models.NonCH4Hydrocarbons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NonCH4Hydrocarbons", (string)null);
                });

            modelBuilder.Entity("Loghid.Models.Oxygen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Oxygen", (string)null);
                });

            modelBuilder.Entity("Loghid.Models.Substance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Substances");
                });

            modelBuilder.Entity("Loghid.Models.SulphurCompounds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SulphurCompounds", (string)null);
                });

            modelBuilder.Entity("Loghid.Models.Water", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsoThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasuredRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Probability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Water", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
